# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nfhw0K7QGRzQWmnxruBPNIXi-65o3sCb
"""

import gradio as gr
import pandas as pd
import smtplib
from email.mime.text import MIMEText
import time

def send_emails(file, sender_email, app_password, subject):
    df = pd.read_csv(file.name)

    # Normalize column names
    df.columns = df.columns.str.lower().str.strip()

    # Column options
    email_options = ["email", "mail", "email address", "mail address"]
    message_options = ["feedback", "message"]

    email_col = None
    message_col = None

    # Detect columns
    for col in df.columns:
        if col in email_options:
            email_col = col
        if col in message_options:
            message_col = col

    if email_col is None:
        return "❌ Email column not found"
    if message_col is None:
        return "❌ Message/Feedback column not found"

    # Lowercase
    df[email_col] = df[email_col].astype(str).str.lower()
    df[message_col] = df[message_col].astype(str)

    # Login
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, app_password)
    except:
        return "❌ Login failed! Check email or app password"

    log = []

    # Send emails
    for index, row in df.iterrows():
        to_email = row[email_col]
        message = row[message_col]

        msg = MIMEText(message)
        msg['Subject'] = subject
        msg['From'] = sender_email
        msg['To'] = to_email

        try:
            server.sendmail(sender_email, to_email, msg.as_string())
            log.append(f"✅ Sent to {to_email}")
        except:
            log.append(f"❌ Failed to {to_email}")

        time.sleep(2)

    server.quit()

    return "\n".join(log)

# UI
interface = gr.Interface(
    fn=send_emails,
    inputs=[
        gr.File(label="Upload CSV"),
        gr.Textbox(label="Your Email"),
        gr.Textbox(label="App Password", type="password"),
        gr.Textbox(label="Subject")
    ],
    outputs="text",
    title="📧 Email Automation System",
    description="⚠️ Use Gmail App Password (not your normal password)\nUpload CSV → Enter details → Send Emails"
)

# ✅ IMPORTANT for Render
interface.launch(server_name="0.0.0.0", server_port=7860)